### ISSUE TITLE
Credits field accepts text input

### ISSUE THREAD

**Issue by madaanpulkit** [jhu-cs-ca-hiring/feedback#5]
### Is there an existing issue (report) for this bug?

- [X] I have searched the existing issues.

### What happened?

Credits field in the form accept text input without warning. But form submission fails without pointing to this reason and the form progress is lost.

### Additional details?

400 Bad Request Error to the Heroku App

### Contact details?

pmadaan2@jhu.edu

**Comment by madooei** [comment]
Thanks for reporting this. It is now fixed. By the way, we just put a team together to further develop this application. You seem to have the right aptitude for this development project. If you are interested to join our team, let me know (`madooei@jhu.edu`).
